# Generated by Django 6.1 on 2026-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discreption', models.TextField(max_length=1000)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
