# Generated by Django 6.1 on 2026-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
