# Generated by Django 6.1 on 2026-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavYoutuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcribers', models.IntegerField()),
            ],
        ),
    ]
