# Generated by Django 6.1 on 2026-08-30 14:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_favyoutuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discreption',
            field=tinymce.models.HTMLField(),
        ),
    ]
